// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7RhWMS4LBxZrZcUaZU7yK9u_kt16Mh64',
    appId: '1:513224798808:web:2af2925234af350090502d',
    messagingSenderId: '513224798808',
    projectId: 'irta-forms-app',
    authDomain: 'irta-forms-app.firebaseapp.com',
    storageBucket: 'irta-forms-app.firebasestorage.app',
    measurementId: 'G-LRF0B1WT21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoIQfXqtdkzsiMluJONPK8r1QISNBC2oo',
    appId: '1:513224798808:android:8f972ef4af1ce32690502d',
    messagingSenderId: '513224798808',
    projectId: 'irta-forms-app',
    storageBucket: 'irta-forms-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC94ILgYf6kX6XFLtxLhVBjzo1Tpwyx7I0',
    appId: '1:513224798808:ios:5ad411b81046c1d790502d',
    messagingSenderId: '513224798808',
    projectId: 'irta-forms-app',
    storageBucket: 'irta-forms-app.firebasestorage.app',
    iosBundleId: 'com.example.irtaFormsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7RhWMS4LBxZrZcUaZU7yK9u_kt16Mh64',
    appId: '1:513224798808:web:cf31f97470bf39cc90502d',
    messagingSenderId: '513224798808',
    projectId: 'irta-forms-app',
    authDomain: 'irta-forms-app.firebaseapp.com',
    storageBucket: 'irta-forms-app.firebasestorage.app',
    measurementId: 'G-Y10H2JF7W2',
  );
}
